### PR TITLE
support async functions in cached/cachedmethod

### PR DESCRIPTION
**Pull request by hephex**
Inspect the wrapped object, if it's a coroutine function await the future.

@tkem I copied and pasted the decorator code from the existing ones, let me know if you think it needs refactoring.

See [inspect.iscoroutinefunction](https://docs.python.org/3/library/inspect.html#inspect.iscoroutinefunction)

### CODE REVIEW

**Comment by tkem** [comment]
Sorry, but I don't think that adding support for async functions/methods into the existing decorators is the right approach. It complicates implementation/maintenance, and - as you may have noticed by now - it's hard to get right while maintaining backwards compatibility with Python versions back to 2.7.
As stated [before](https://github.com/tkem/cachetools/issues/92#issuecomment-418536503), I'd rather like to see this released as a separate module - preferably maintained by someone who is more familiar with all the `async` stuff than I am.

**Comment by hephex** [comment]
@tkem thanks for the feedback and sorry for the duplicate _topic_. Yes, supporting 2.7 and 3.5+ at the same time is quite tricky. I'll create a new package for the _async decorators_.

**Comment by tkem** [comment]
@hephex: That sounds great! And sorry for the delay and letting you struggle for so long - real life got in the way...

**Comment by halfdanrump** [comment]
@hephex Awesome!

**Pull request closed without merging**
