### PR TITLE
Set minimum permissions for ci.yml

### PR DESCRIPTION
**Pull request by gabibguti**
Resolves https://github.com/tkem/cachetools/issues/261

### CODE REVIEW

**Comment by gabibguti** [comment]
@tkem The workflow runs for a set of python versions and some python versions are failing in my fork. May I ask you to run the workflow in this draft PR to see if it's happening here too?

**Comment by gabibguti** [comment]
Thanks. I will take a look why is this hapenning.

**Comment by tkem** [comment]
@gabibguti: Not your fault, apparently the most recent version of `black` would like to format things a bit differently.
I'll pin a working `black` version in the master branch ASAP, then you should be able to rebase without problems.

**Comment by gabibguti** [comment]
@tkem Oh ok, thanks for identifying that! I'll wait to rebase then :)

**Comment by gabibguti** [comment]
All good now!

**Comment by tkem** [comment]
Thanks!

**Pull request merged**
