### PR TITLE
Replacing try-except by .get() for better performance

### PR DESCRIPTION
**Pull request by YoniMelki**

### CODE REVIEW

**Comment by tkem** [comment]
Do you actually have measurements to support your claim?
Plus, what if anybody puts `None` as a value into a cache on purpose?

**Comment by YoniMelki** [comment]
> Do you actually have measurements to support your claim? Plus, what if anybody puts `None` as a value into a cache on purpose?

**Comment by tkem** [comment]
While sentinel objects are the way to go for tackling `None` values (see e.g. https://github.com/python/cpython/blob/3.11/Lib/functools.py#L527), I'd really like to see some "hard facts", i.e. measurements taken using actual cache implementations, and not some reference to some generic discussion of the topic.

**Comment by tkem** [comment]
That doesn't mean replacing the `try-except` code is a bad thing, it's just that more data is needed to make a decision.

**Pull request closed without merging**
