### PR TITLE
Add MRU cache implementation

### PR DESCRIPTION
**Pull request by dargueta**
Adds to #114

### CODE REVIEW

**Comment by tkem** [comment]
Thanks! Looks very nice on first sight, additional points for keeping coverage at 100% and providing a single commit ;-)
I'll have to find time later this week to have a closer look, but I'm quite confident this can be merged as is.

**Comment by tkem** [comment]
Merged into https://github.com/tkem/cachetools/tree/dev/4.2.0, thanks!

**Comment by dargueta** [comment]
I take it I should close the PR then?

**Comment by tkem** [comment]
We could also leave it open until v4.2 gets released and is merged into master. Then it will close automatically. As you like.

**Pull request closed without merging**
