### PR TITLE
Drop support for Python 2.7 and 3.4

### LINKED ISSUE #143: Drop Python 2.7 support
Python 2 will reach end of life on Jan 1 2020. Although `cachetools` doesn't include much code for backward-compatibility, some small things may be cleaned up by dropping Python 2 support, e.g. setting `__wrapped__` on decorated functions explicitly.

### PR DESCRIPTION
**Pull request by hugovk**
Fixes #143. 

Also upgrade tested PyPy3 from Python 3.5.3/PyPy 5.10.1 to Python 3.6.1/PyPy 7.1.1-beta0.

### CODE REVIEW

**Comment by hugovk** [comment]
Coveralls shows some other old bits of code that may be removed, I'll update the PR later.

**Comment by hugovk** [comment]
> Coveralls shows some other old bits of code that may be removed, I'll update the PR later.

✅ Done!

**Comment by tkem** [comment]
Thanks for your effort! I'll look into this closer when I start development on the next major version of cachetools!

**Comment by tkem** [comment]
Obsoleted by the dev/4.0.0 branch.

**Pull request closed without merging**
