### PR TITLE
Add callback function register on construct

### PR DESCRIPTION
**Pull request by joe1234wu**
This feature can able let caller do the callback function when the data going to pop

### CODE REVIEW

**Comment by tkem** [comment]
Why would you do that? Why not override `popitem()` directly?

**Comment by joe1234wu** [comment]
Since If I need to override popitem(), then I need to Inherit from one of the Cache.
For example, most of all I am using LRUCache and TTLCache, but I have different handling when using each of Cache.
Or more complex, I have five different LRUCache but want different popitem handing.
In this situation, you suggest that I need to Inherit and define five different Class to fulfill.

But with the callback function, I can just define five callback function and use the same LRUCache.
For me, maybe it will be more clean in implementation.

**Comment by tkem** [comment]
You could implement a class decorator that wraps a cache class with a custom `popitem` method; for example (quickly hacked together, not something I recommend for production use):
```
def CallbackCache(callback):
    def decorator(cls):
        class Wrapper(cls):
            def popitem(self):
                key, value = cls.popitem(self)
                callback(key, value)
                return key, value
        return Wrapper
    return decorator

def printpop(key, value):
    print('pop item (%r, %r)' % (key, value))

@CallbackCache(printpop)
class PrintCache(cachetools.LRUCache):
    pass

# or, if you prefer

PrintCache = CallbackCache(printpop)(cachetools.LRUCache)

cache = PrintCache(maxsize=3)
```
Frankly, I don't plan to add more arguments to the cache constructor. I'd actually like to get rid of the `missing` and `getsizeof` arguments, if I can provide a sensible alternative, possibly using decorators. However, this isn't high on my agenda and won't happen too soon.

**Comment by tkem** [comment]
No need to add this functionality to the library - can already be implemented by clients without much effort.

**Pull request closed without merging**
